// Edit this file to adjust the symbol order on each reel.
export type ReelSymbol = 'RED_7' | 'BLUE_7' | 'BAR' | 'BELL' | 'CHERRY' | 'REPLAY' | 'MELON'

export const REEL_SYMBOLS_PER_STRIP = 21

export const REEL_STRIPS = [
  [
    'MELON',
    'REPLAY',
    'BELL',
    'MELON',
    'REPLAY',
    'BELL',
    'BLUE_7',
    'CHERRY',
    'BAR',
    'MELON',
    'REPLAY',
    'BELL',
    'BLUE_7',
    'BLUE_7',
    'BLUE_7',
    'MELON',
    'REPLAY',
    'BELL',
    'BAR',
    'CHERRY',
    'RED_7',
  ],
  [
    'CHERRY',
    'BELL',
    'REPLAY',
    'MELON',
    'BELL',
    'CHERRY',
    'RED_7',
    'REPLAY',
    'MELON',
    'BELL',
    'CHERRY',
    'BAR',
    'REPLAY',
    'CHERRY',
    'BELL',
    'REPLAY',
    'BLUE_7',
    'CHERRY',
    'BELL',
    'REPLAY',
    'RED_7',
  ],
  [
    'CHERRY',
    'BAR',
    'REPLAY',
    'BELL',
    'CHERRY',
    'MELON',
    'REPLAY',
    'BELL',
    'CHERRY',
    'REPLAY',
    'BAR',
    'BELL',
    'BLUE_7',
    'MELON',
    'REPLAY',
    'BELL',
    'BAR',
    'MELON',
    'REPLAY',
    'BELL',
    'RED_7',
  ],
] satisfies readonly [readonly ReelSymbol[], readonly ReelSymbol[], readonly ReelSymbol[]]
